add eth_getCode method
nlordell/ethcrates-rs pull request #2
Opened 2023-08-24 16:13 UTC by bh2smith

So far I have only added what I believe to be the interface. I am not sure if there are other parts of the code that need to be altered for this to work. Didn't see any tests I could work from. Please let me know if there is more to be done here.

2023-08-24 20:20 UTC, nlordell requested changes

2023-08-24 20:20 UTC, nlordell commented on crates/ethrpc/src/lib.rs
> +        (Address,) => Option<Vec<u8>>;
nit: can you indent this like the method above? Also, I think this needs a serialization directive (see the other method that returns a Vec<u8>)

2023-08-25 06:51 UTC, bh2smith commented on crates/ethrpc/src/lib.rs
> +        (Address,) => Option<Vec<u8>>;
Right. I noticed the need for "serialization directive" but wasn't sure how it worked with the option there. Was waiting for you to say so
Etching about that.

2023-08-25 07:13 UTC, bh2smith commented
It appears there is also an Optional Block number that can be provided to such a request. This is a feature I have never used, because I can't even imagine the reason for this.

one can specify: "latest", "earliest" or "pending". I suppose it wouldn't be so difficult to add here, but I would love to understand the difference first.

2023-08-25 07:14 UTC, bh2smith commented on crates/ethrpc/src/lib.rs
> +        (Address,) => Option<Vec<u8>>;
Done, but compiler doesn't seem to like it.

2023-08-25 07:21 UTC, bh2smith commented
Ya, so as suspected the serializer doesn't like the Option:

```
the trait `AsRef<[u8]>` is not implemented for `std::option::Option<Vec<u8>>`
```

I can try to implement this.

2023-08-25 07:30 UTC, bh2smith commented
Turns out the Option was not necessary since the endpoint returns 0x when no code is available at the given address

2023-08-25 13:13 UTC, nlordell commented on crates/ethrpc/src/lib.rs
> +        /// Returns code at a given address
```suggestion
        /// Returns code at a given address.
```

2023-08-25 13:13 UTC, nlordell approved these changes

2023-08-25 13:15 UTC, merged